openapi: 3.0.0
info:
  title: Supabase GoTrue
  description: "A JWT based API for managing users and issuing JWT tokens "
  version: 0.0.1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  parameters:
    redirect_to:
      name: redirect_to
      in: query
      schema:
        type: string
        format: uri
  schemas:
    UserCredentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        phone:
          type: string
        refresh_token:
          type: string
    SignUpRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        phone:
          type: string
        data:
          type: object
        gotrue_meta_security:
          $ref: "#/components/schemas/GoTrueMetaSecurity"
    Session:
      type: object
      properties:
        provider_token:
          type: string
          description: "The oauth provider token. If present, this can be used to make external API requests to the oauth provider used."
        provider_refresh_token:
          type: string
          description: "The oauth provider refresh token. If present, this can be used to refresh the provider_token via the oauth provider's API. Not all oauth providers return a provider refresh token. If the provider_refresh_token is missing, please refer to the oauth provider's documentation for information on how to obtain the provider refresh token."
        access_token:
          type: string
          description: "The access token jwt. It is recommended to set the JWT_EXPIRY to a shorter expiry value."
        token_type:
          type: string
        expires_in:
          type: number
          description: "The number of seconds until the token expires (since it was issued). Returned when a login is confirmed."
        refresh_token:
          type: string
          description: "A one-time used refresh token that never expires."
        user:
          $ref: "#/components/schemas/User"
      required:
        - access_token
        - token_type
        - expires_in
        - refresh_token
        - user
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        app_metadata:
          type: object
        user_metadata:
          type: object
        aud:
          type: string
        confirmation_sent_at:
          type: string
          format: date-time
        recovery_sent_at:
          type: string
          format: date-time
        email_change_sent_at:
          type: string
          format: date-time
        new_email:
          type: string
        invited_at:
          type: string
          format: date-time
        action_link:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        created_at:
          type: string
          format: date-time
        confirmed_at:
          type: string
          format: date-time
        email_confirmed_at:
          type: string
          format: date-time
        phone_confirmed_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        role:
          type: string
        updated_at:
          type: string
          format: date-time
        identities:
          type: array
          items:
            $ref: "#/components/schemas/UserIdentity"
      required:
        - id
        - app_metadata
        - user_metadata
        - aud
        - created_at
        - updated_at
    UserIdentity:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
          format: uuid
        identity_data:
          type: object
        provider:
          type: string
        created_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - user_id
        - identity_data
        - provider
        - created_at
        - last_sign_in_at
        - updated_at
    Provider:
      type: string
      enum:
        - apple
        - azure
        - bitbucket
        - discord
        - email
        - facebook
        - github
        - gitlab
        - google
        - keycloak
        - linkedin
        - notion
        - slack
        - spotify
        - twitch
        - twitter
        - workos
    OpenIDConnectCredentials:
      type: object
      properties:
        id_token:
          type: string
        nonce:
          type: string
        client_id:
          type: string
        issuer:
          type: string
        provider:
          $ref: "#/components/schemas/Provider"
      required:
        - id_token
        - nonce
    GoTrueMetaSecurity:
      type: object
      properties:
        hcaptcha_token:
          type: string
      required:
        - hcaptcha_token
    OTPParams:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
        create_user:
          type: boolean
          default: true
        data:
          type: object
        gotrue_meta_security:
          $ref: "#/components/schemas/GoTrueMetaSecurity"
    VerifyOTPParams:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
        token:
          type: string
        type:
          $ref: "#/components/schemas/OTPType"
        gotrue_meta_security:
          $ref: "#/components/schemas/GoTrueMetaSecurity"
      required:
        - token
        - type
    OTPType:
      type: string
      enum:
        - sms
        - phone_change
        - signup
        - invite
        - magiclink
        - recovery
        - email_change
    AuthResponse:
      oneOf:
        - $ref: "#/components/schemas/Session"
        - $ref: "#/components/schemas/User"
    UserAttributes:
      type: object
      properties:
        email:
          type: string
          description: "The user's email."
        phone:
          type: string
          description: "The user's phone."
        password:
          type: string
          description: "The user's password."
        email_change_token:
          type: string
          description: "An email change token."
        data:
          type: object
          description: "A custom data object to store the user's metadata. This maps to the `auth.users.user_metadata` column. The `data` should be a JSON object that includes user-specific info, such as their first and last name."
    RecoverParams:
      type: object
      properties:
        email:
          type: string
        gotrue_meta_security:
          $ref: "#/components/schemas/GoTrueMetaSecurity"
      required:
        - email

paths:
  /token:
    post:
      parameters:
        - name: grant_type
          in: query
          required: true
          schema:
            type: string
            enum:
              - password
              - refresh_token
              - id_token
        - $ref: "#/components/parameters/redirect_to"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/UserCredentials"
                - $ref: "#/components/schemas/OpenIDConnectCredentials"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
  /signup:
    summary: ""
    post:
      parameters:
        - $ref: "#/components/parameters/redirect_to"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
  /otp:
    summary: ""
    post:
      parameters:
        - $ref: "#/components/parameters/redirect_to"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OTPParams"
      responses:
        default:
          description: ""
  /verify:
    summary: ""
    post:
      parameters:
        - $ref: "#/components/parameters/redirect_to"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyOTPParams"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
  /user:
    summary: ""
    get:
      security:
        - BearerAuth: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      security:
        - BearerAuth: []
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAttributes"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /logout:
    summary: ""
    post:
      security:
        - BearerAuth: []
      responses:
        default:
          description: ""
  /recover:
    summary: ""
    post:
      parameters:
        - $ref: "#/components/parameters/redirect_to"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecoverParams"
      responses:
        default:
          description: ""
