openapi: 3.0.0
info:
  title: Supabase GoTrue
  description: "A JWT based API for managing users and issuing JWT tokens "
  version: 0.0.1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  parameters:
    redirect_url:
      name: redirect_url
      in: query
      schema:
        type: string
        format: uri
  schemas:
    UserCredentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        phone:
          type: string
        refresh_token:
          type: string
    SignUpRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        phone:
          type: string
        data:
          type: object
        gotrue_meta_security:
          $ref: "#/components/schemas/GoTrueMetaSecurity"
    Session:
      type: object
      properties:
        provider_token:
          type: string
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: number
        refresh_token:
          type: string
        user:
          $ref: "#/components/schemas/User"
      required:
        - access_token
        - token_type
        - expires_in
        - refresh_token
        - user
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        app_metadata:
          type: object
        user_metadata:
          type: object
        aud:
          type: string
        confirmation_sent_at:
          type: string
          format: date-time
        recovery_sent_at:
          type: string
          format: date-time
        invited_at:
          type: string
          format: date-time
        action_link:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        created_at:
          type: string
          format: date-time
        confirmed_at:
          type: string
          format: date-time
        email_confirmed_at:
          type: string
          format: date-time
        phone_confirmed_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        role:
          type: string
        updated_at:
          type: string
          format: date-time
        identities:
          type: array
          items:
            $ref: "#/components/schemas/UserIdentity"
      required:
        - id
        - app_metadata
        - user_metadata
        - aud
        - created_at
        - updated_at
    UserIdentity:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        identity_data:
          type: object
        provider:
          $ref: "#/components/schemas/Provider"
        created_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - user_id
        - identity_data
        - provider
        - created_at
        - last_sign_in_at
        - updated_at
    Provider:
      type: string
      enum:
        - apple
        - azure
        - bitbucket
        - discord
        - email
        - facebook
        - github
        - gitlab
        - google
        - keycloak
        - linkedin
        - notion
        - slack
        - spotify
        - twitch
        - twitter
        - workos
    OpenIDConnectCredentials:
      type: object
      properties:
        id_token:
          type: string
        nonce:
          type: string
        client_id:
          type: string
        issuer:
          type: string
        provider:
          $ref: "#/components/schemas/Provider"
      required:
        - id_token
        - nonce
    GoTrueMetaSecurity:
      type: object
      properties:
        hcaptcha_token:
          type: string
      required:
        - hcaptcha_token
    OTPParams:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
        create_user:
          type: boolean
          default: "true"
        gotrue_meta_security:
          $ref: "#/components/schemas/GoTrueMetaSecurity"
    VerifyMobileOTPParams:
      type: object
      properties:
        phone:
          type: string
        token:
          type: string
        type:
          type: string
          enum:
            - sms
      required:
        - phone
        - token
        - type
    VerifyEmailOTPParams:
      type: object
      properties:
        email:
          type: string
        token:
          type: string
        type:
          type: string
          enum:
            - signup
            - invite
            - magiclink
            - recovery
            - email_change
      required:
        - email
        - token
        - type
    VerifyOTPParams:
      oneOf:
        - $ref: "#/components/schemas/VerifyMobileOTPParams"
        - $ref: "#/components/schemas/VerifyEmailOTPParams"
    SessionOrUser:
      oneOf:
        - $ref: "#/components/schemas/Session"
        - $ref: "#/components/schemas/User"
    UserAttributes:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
        password:
          type: string
        email_change_token:
          type: string
        data:
          type: object

paths:
  /token:
    summary: ""
    post:
      parameters:
        - name: grant_type
          in: query
          required: true
          schema:
            type: string
            enum:
              - password
              - refresh_token
              - id_token
        - $ref: "#/components/parameters/redirect_url"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/UserCredentials"
                - $ref: "#/components/schemas/OpenIDConnectCredentials"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
  /signup:
    summary: ""
    post:
      parameters:
        - $ref: "#/components/parameters/redirect_url"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionOrUser"
  /otp:
    summary: ""
    post:
      parameters:
        - $ref: "#/components/parameters/redirect_url"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OTPParams"
      responses:
        default:
          description: ""
  /verify:
    summary: ""
    post:
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyOTPParams"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionOrUser"
  /user:
    summary: ""
    get:
      security:
        - BearerAuth: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      security:
        - BearerAuth: []
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAttributes"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /logout:
    summary: ""
    post:
      security:
        - BearerAuth: []
      responses:
        default:
          description: ""
