name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test-library

  example:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy Secrets file
        run: cp Examples/Shared/Sources/_Secrets.swift Examples/Shared/Sources/Secrets.swift
      - name: Build example
        run: make build-example
